### PR TITLE
feat: add Swagger JSON generation and docker-compose for Swagger UI

### PR DESCRIPTION
**Pull request by silathdiir**

### CODE REVIEW

**Comment by silathdiir** [comment]
@lispc @HAOYUatHZ I add a README for this project, and update Makefile. Please help review if you have time. Thanks.

**Comment by HAOYUatHZ** [comment]
1. I can't run `make gensw` successfully
```
❰chris❙~/gitfiles/fluidex/orchestra(git:first-version-swagger-ui)❱✔≻ make goinstall
go mod tidy
bash go-install.sh
❰chris❙~/gitfiles/fluidex/orchestra(git:first-version-swagger-ui)❱✔≻ make gensw 
go mod tidy
bash go-install.sh
protoc -I. -Iproto/third_party/googleapis --openapiv2_out . --openapiv2_opt logtostderr=true proto/exchange/matchengine.proto
proto/exchange/matchengine.proto:103:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.
proto/exchange/matchengine.proto:127:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.
proto/exchange/matchengine.proto:128:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.
make: *** [Makefile:26: gensw] Error 1
❰chris❙~/gitfiles/fluidex/orchestra(git:first-version-swagger-ui)❱✘≻ make runswui 
cd proto && protoc -Ithird_party/googleapis -I. --include_imports --include_source_info --descriptor_set_out=exchange/matchengine.pb exchange/matchengine.proto
exchange/matchengine.proto:103:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.
exchange/matchengine.proto:127:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.
exchange/matchengine.proto:128:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.
make: *** [Makefile:21: genpb] Error 1
❰chris❙~/gitfiles/fluidex/orchestra(git:first-version-swagger-ui)❱✘≻
```

**Comment by silathdiir** [comment]
> I can't run `make gensw` successfully
> 

@HAOYUatHZ Could you help give the version of `protoc` as below?
```
> protoc --version

libprotoc 3.17.3
```

**Comment by HAOYUatHZ** [comment]
> protoc --version

```
libprotoc 3.6.1
```

OK I will upgrade it.

**Review by HAOYUatHZ — APPROVED** [review]

**Pull request merged**
